version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: dbfinancial
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dbmysql
      MYSQL_DATABASE: financialdb
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend

  api:
    image: node:10.16-slim
    container_name: 'financial-api'
    ports:
      - 3333:3333
    working_dir: '/home/node/app'
    volumes:
      - ./:/home/node/app
    command: yarn dev
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'
